import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillMail, AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import verca from '../public/veronika-vokounova.jpg'


import web1 from '../public/web1.jpg';
import web2 from '../public/web2.jpg';
import web3 from '../public/web3.jpg';
import web4 from '../public/web4.jpg';
import web5 from '../public/web5.jpg';
import web6 from '../public/web6.jpg';

import {useState} from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Veronika Vokounová Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 e'>
      <section className='min-h-screen dark:text-white'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-montserrat'>Junior Web Developer</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
            </li>
            <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
            </li>
          </ul>
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Veronika Vokounová</h2>
          <h3 className='text-2xl py-2 md:text-3xl'>Junior Web Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Freelancer providing services for programming needs. Join me down below.</p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white'>
          <a href='mailto:vero.vokounova@gmail.com'>
            <AiFillMail /></a>

          <a href='https://github.com/vercik13?tab=repositories'>
            <AiFillGithub /></a>

          <a href='https://www.linkedin.com/in/veronika-vokounova/'>
            <AiFillLinkedin /></a>

        </div>
        
        <div >
        <Image className='relative mx-auto rounded-full w-80 h-80 object-cover mt-20' src={verca} /> 
        </div>
      </section>

      
      <section className='dark:text-white'>
        <div>
          <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Since the beginning of my journey</p>
        </div>


        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          <div className='basis-1/3 flex-1' >
            <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} />
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} />
          </div>
        </div>
      </section>
      </main>


    </div>
  )
}
